#!/bin/sh
#
#
# PROVIDE: beamium
# REQUIRE: DAEMON
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable this service:
#
# beamium_enable:       Set to NO by default. Set it to YES to enable it.
# beamium conf: 	Directory where beamium configuration file 
#	  		  is stored
# beamium_user:         The user account beamium daemon runs as what
#                         you want it to be.
#                         Default: beamium
# beamium_group:        The group account beamium daemon runs as what
#                         you want it to be.
#                         Default: beamium

. /etc/rc.subr

name=beamium
rcvar=beamium_enable

start_cmd="${name}_start"
stop_cmd="${name}_stop"

load_rc_config $name

: ${beamium_enable:=NO}
: ${beamium_conf=/etc/beamium/config.yaml}
: ${beamium_user:=beamium}
: ${beamium_log=/var/log/beamium/beamium.log}
beamium_group=${beamium_group:-$beamium_user}

command=/usr/bin/beamium
pidfile=/var/run/beamium.pid
beamium_flags="${beamium_conf:+-c ${beamium_conf}}"


get_pid() {
    cat "$pidfile"
}

is_running() {
    [ -f "$pidfile" ] && ps `get_pid` > /dev/null 2>&1
}

beamium_start() {
    if is_running; then
        echo "Already started"
    else
        echo 'Starting beamium'
	/usr/sbin/daemon -cf -p ${pidfile} -u ${beamium_user} -o ${beamium_log} ${command} ${beamium_flags}

        if ! is_running; then
            echo "Unable to start, see log"
            exit 1
        fi
    fi
    echo "Started"
}

beamium_stop() {
    if is_running; then
        echo -n "Stopping beamium.."
        kill -2 `get_pid`
        for i in {1..10}
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pidfile" ]; then
                rm "$pidfile"
            fi
        fi
    else
        echo "Not running"
    fi
}


beamium_status() {
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
}

beamium_cleanup() {
    [ -f ${pidfile} ] && rm ${pidfile}
}

run_rc_command $1

