#!/bin/bash
pw groupadd -n beamium
pw useradd beamium -g beamium -d /nonexistent -L daemon -c "Beamium user"
mkdir -p /opt/beamium
chown -R beamium:beamium /opt/beamium
mkdir -p /var/log/beamium
chown -R beamium:beamium /var/log/beamium
